name: morning
on:
  schedule:
  - cron:  '02 0 * * *'
  workflow_dispatch:

jobs:
  morning:
    runs-on: ubuntu-latest
    name: send morning to your girlfriend
    env:
      APP_ID: ${{ secrets.APP_ID }}
      APP_SECRET: ${{ secrets.APP_SECRET }}
      TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
      USER_IDS: ${{ secrets.USER_IDS }}
      NAMES: ${{ secrets.NAMES }}
      LOVE_DATE: ${{ secrets.LOVE_DATE }}
      BIRTHDAY: ${{ secrets.BIRTHDAY }}
      CITY: ${{ secrets.CITY }}
      PROVINCE: ${{ secrets.PROVINCE }}
      PUSHKEYS: ${{ secrets.PUSHKEYS }}

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ env.GITHUB_REF_NAME }}

    - name: sender
      uses: actions/setup-python@v2

    - run: pip install -r ./requirements.txt && python ./morning.py

